# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('experiment_type', models.CharField(max_length=32)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
                ('units', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('jawbone_id', models.CharField(blank=True, default=b'', max_length=32)),
                ('jawbone_timezone', models.CharField(blank=True, default=b'', max_length=32)),
                ('jawbone_datestring', models.CharField(blank=True, default=b'', max_length=8)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='happy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='jawbone_access_token',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='jawbone_reset_token',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(choices=[(b'nativeamerican', b'American Indian or Alaska Native'), (b'hawaiian', b'Hawaiian or Other Pacific Islander'), (b'asian', b'Asian or Asian American'), (b'black', b'Black or African American'), (b'latino', b'Hispanic or Latino'), (b'white', b'Non-Hispanic White'), (b'other', b'Other')], default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_quality',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL),
        ),
    ]
