# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jawbone_access_token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='jawbone_reset_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
