# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160711_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('checkin_time', models.DateTimeField()),
                ('did_follow_instructions', models.IntegerField()),
                ('happiness', models.IntegerField()),
                ('stress', models.IntegerField()),
                ('productivity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='checkin',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='app.Experiment'),
        ),
    ]
