# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_experiment_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jawbone_user_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
