# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_jawbone_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawboneMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('jawbone_id', models.CharField(blank=True, default=b'', max_length=32)),
                ('jawbone_timezone', models.CharField(blank=True, default=b'', max_length=32)),
                ('jawbone_datestring', models.CharField(blank=True, default=b'', max_length=8)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=12)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('raw_jawbone_object', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
