# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160726_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jawbonemeasurement',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='jawbonemeasurement',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='jawbonemeasurement',
            name='key',
        ),
    ]
