# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160726_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
