# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160817_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='instructions',
            new_name='result_instructions',
        ),
        migrations.AddField(
            model_name='checkin',
            name='result_status',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
