# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_experiment_result_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='result',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='result_text',
        ),
        migrations.AddField(
            model_name='experiment',
            name='current_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='reported_normal_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='result_confidence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='result_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='stage_start_dates',
            field=models.TextField(default=b'[null, null, null]'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='stage_target_values',
            field=models.TextField(default=b'[null, null, null]'),
        ),
    ]
