# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='reported_normal_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='result_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='result_value',
            field=models.FloatField(default=0),
        ),
    ]
