# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160922_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='reported_normal_value',
        ),
        migrations.AddField(
            model_name='checkin',
            name='leisure_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='initial_stage_average',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='stage_results',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AddField(
            model_name='jawbonemeasurement',
            name='awake_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
