# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20161011_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='app_efficacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_efficacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='self_efficacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
