# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20161014_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='app_version',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
    ]
