# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashreport',
            name='is_silent',
        ),
    ]
