# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acra', '0002_remove_crashreport_is_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashreport',
            name='is_silent',
            field=models.BooleanField(default=False),
        ),
    ]
